### ISSUE TITLE
Possible bug in `unique` for partial InlineString

### ISSUE THREAD

**Issue by nilshg** [JuliaStrings/InlineStrings.jl#32]
Just came across this when working with a column of prices in British pounds, all of which were prepended with `GBP`. In trying to check whether indeed all entries in the (`Vector{String15}`) column start with `GBP`, I did `unique(first.(my_col, 3))` and was surprised to get back a length 196 vector with all entries showing `GBP`. 

A reproducer is:

```
julia> using InlineStrings

julia> x = inlinestrings(["GBP$i" for i ∈ rand(1.0:0.01:500.0, 1_000)]);

julia> length(unique(first.(x, 3)))
994

julia> length(unique(string.(first.(x, 3))))
1
```

The fact that there are 994 (rather than 1,000) unique results suggests to me that where the entire string is the same (because the same "price" was randomly chosen twice in setup of the xample), the first three characters are seen as the same by `unique` as well.

Is this intended, i.e. is there some fundamental issue with working with "`SubInlineString`s" that means I shouldn't be doing what I'm doing or is this a bug?

**Comment by bkamins** [comment]
It is a bug.

**Comment by nickrobinson251** [comment]
I think the bug is in the interaction between `first`/`last` and the definition of `==` for inline string of the same type.

```julia
julia> abc = InlineString3("abc")
"abc"

julia> first(abc, 2) == "ab"
true

julia> first(abc, 2) == InlineString15("ab")
true

julia> first(abc, 2) == InlineString3("ab")  # whoops!
false
```

I think because `first` only changes the final byte which tracks the length of the string, whereas our definition of `==`/`cmp` assumes that if the final byte says the string has length 2 then only the first 2 bytes are non-zero

```julia
julia> bitstring(abc)
"01100001011000100110001100000011"

julia> bitstring(first(abc, 2))
"01100001011000100110001100000010"

julia> bitstring(InlineString3("ab"))
"01100001011000100000000000000010"
```
So i suppose we could change `first` to zero-out all the unused bits, or change our definition of `==`/`cmp`

It seems this bug is fixed, and all current tests pass, if we just remove this definitions:
https://github.com/JuliaStrings/InlineStrings.jl/blob/ffbc1dee80706f2b465855517146a3e3379924fa/src/InlineStrings.jl#L277
https://github.com/JuliaStrings/InlineStrings.jl/blob/ffbc1dee80706f2b465855517146a3e3379924fa/src/InlineStrings.jl#L286-L287

**Comment by quinnj** [comment]
Thanks for the report @nilshg! PR up to fix: https://github.com/JuliaStrings/InlineStrings.jl/pull/33. I started reworking the internal representation a bit ago, but didn't get it finished, so I'm going to try and reprioritize that do some more stress testing on all the inline strings. We need to improve its support across the ecosystem as well.

**Comment by nilshg** [comment]
Brilliant, thanks a lot all! Now we just need a new release ;)

**Comment by nickrobinson251** [comment]
> Now we just need a new release ;)

New release with the fix should be out 🤞 https://github.com/JuliaStrings/InlineStrings.jl/releases/tag/v1.1.3

**Comment by nilshg** [comment]
Hooray! Thanks so much - I use the package for data analysis in the context of litigation where code has to be disclosed in court, so it's always a bit awkward to depend on unreleased versions of packages.
